version: '3.8'

services:
  webdav:
    image: python:3.12  # 使用官方 Python 3.12 镜像
    container_name: webdav_server
    restart: always  # 使容器在异常退出时自动重启
    working_dir: /app  # 设置容器内的工作目录
    volumes:
      - .:/app  # 挂载当前目录到容器内 `/app`
    ports:
      - "4040:8080" # 将容器的8080端口映射到主机的4040端口
    environment:
      - USERNAME=admin  # 设置 WebDAV 访问用户名
      - PASSWORD=123456  # 设置 WebDAV 访问密码
    command: >
      sh -c "pip install wsgidav==4.3.3 werkzeug==3.1.3 cheroot==10.0.1 
      && python dav.py"
